name = mod_mcl_signs
title = Standalone MCL Signs
description = A standalone signs mod converted from Mineclonia.
author = TesterSakage
depends = 
optional_depends = default, mcl_core, mcl_mangrove, mcl_cherry_blossom, mcl_bamboo, mcl_crimson, mcl_lanterns, mcl_mesh_items
